nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

npmPublishRegistry: "https://registry.npmjs.org"
npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: ${NODE_AUTH_TOKEN:-}

yarnPath: .yarn/releases/yarn-3.6.4.cjs
